### ISSUE TITLE
Product Vision Statment

### ISSUE THREAD

**Issue by dhawk19** [dhawk19/SWE_Project2#1]
Write a product vision statement. Please follow the format provided in the Chapter 2 lecture notes.

**Comment by almightysnipes** [comment]
[visionstatement.txt](https://github.com/dhawk19/SWE_Project2/files/9832037/visionstatement.txt)
[README.md](https://github.com/dhawk19/SWE_Project2/files/9832039/README.md)

**Comment by dhawk19** [comment]
Thanks, Henry!

**Comment by dhawk19** [comment]
Added product vision statement to README file.
